# Generated by Django 4.2.5 on 2023-12-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'storage', 'verbose_name_plural': 'storage'},
        ),
    ]
